export function cn(...classes) { return classes.filter(Boolean).join(' ') }
export function formatCurrency(amount) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(amount || 0) }
export function formatDate(date) { if (!date) return 'N/A'; return new Date(date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) }
export function formatDateTime(date) { if (!date) return 'N/A'; return new Date(date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }) }
export function getDaysOverdue(dueDate) { const today = new Date(); today.setHours(0,0,0,0); const due = new Date(dueDate); due.setHours(0,0,0,0); if (today <= due) return 0; return Math.ceil((today - due) / (1000*60*60*24)) }
export function getSharingDetails(type) { const details = { single: { label:'Single Sharing', icon:'👤', capacity:1, description:'Private room for 1 person' }, double: { label:'Double Sharing', icon:'👥', capacity:2, description:'Shared room for 2 persons' }, triple: { label:'Triple Sharing', icon:'👥👤', capacity:3, description:'Shared room for 3 persons' }, four: { label:'Four Sharing', icon:'👥👥', capacity:4, description:'Shared room for 4 persons' }, five: { label:'Five Sharing', icon:'👥👥👤', capacity:5, description:'Shared room for 5 persons' }, six: { label:'Six Sharing', icon:'👥👥👥', capacity:6, description:'Shared room for 6 persons' }, dormitory: { label:'Dormitory', icon:'🏘️', capacity:8, description:'Large shared room' } }; return details[type] || details.double }
export function getPropertyTypeLabel(type) { const types = { boys:'👨 Boys PG', girls:'👩 Girls PG', 'co-ed':'👥 Co-ed PG', professionals:'💼 Working Professionals' }; return types[type] || type }
export function cleanPhoneNumber(phone) { if (!phone) return ''; return phone.toString().replace(/^\+91/, '').replace(/\s/g, '').trim() }
export function calculateRentDueStatus(tenant) { if (!tenant) return { status:'paid', message:'', daysUntilDue:null, dueAmount:0, dueDate:null }; const today = new Date(); const joinDate = new Date(tenant.move_in_date); let monthsSinceJoin = (today.getFullYear() - joinDate.getFullYear()) * 12 + (today.getMonth() - joinDate.getMonth()); if (today.getDate() < joinDate.getDate()) monthsSinceJoin -= 1; const monthsPaid = Math.floor((tenant.total_paid || 0) / tenant.rent_amount); const isCurrentMonthPaid = monthsPaid > monthsSinceJoin; if (isCurrentMonthPaid || (tenant.pending_amount === 0 && tenant.rent_status === 'paid')) { const nextDueDate = new Date(today.getFullYear(), today.getMonth() + 1, joinDate.getDate()); if (nextDueDate.getDate() !== joinDate.getDate()) nextDueDate.setDate(0); const daysUntilDue = Math.ceil((nextDueDate - today) / (1000*60*60*24)); return { status:'paid', message:`Paid ✓ | Next due on ${formatDate(nextDueDate)}`, daysUntilDue, dueAmount:0, dueDate:nextDueDate } } const expectedDate = new Date(today.getFullYear(), today.getMonth(), joinDate.getDate()); if (expectedDate.getDate() !== joinDate.getDate()) expectedDate.setDate(0); const daysUntilDue = Math.ceil((expectedDate - today) / (1000*60*60*24)); const pendingAmount = tenant.pending_amount || tenant.rent_amount; if (daysUntilDue < 0) { return { status:'overdue', message:`Overdue by ${Math.abs(daysUntilDue)} days`, daysUntilDue, dueAmount:pendingAmount, dueDate:expectedDate, urgent:true } } else if (daysUntilDue === 0) { return { status:'due_today', message:'Due today!', daysUntilDue:0, dueAmount:pendingAmount, dueDate:expectedDate, urgent:true } } else if (daysUntilDue <= 5) { return { status:'due_soon', message:`Due in ${daysUntilDue} day${daysUntilDue!==1?'s':''}`, daysUntilDue, dueAmount:pendingAmount, dueDate:expectedDate, urgent:true } } else { return { status:'pending', message:`Due on ${formatDate(expectedDate)}`, daysUntilDue, dueAmount:pendingAmount, dueDate:expectedDate, urgent:false } } }
