const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { calculateCanonicalRentDue, anchoredDate, formatRentDueLabel } = require('../lib/rentDue')
const { enrichTenantRentStatus, filterTenantsByRentStatus, summarizeTenantRentStatuses } = require('../lib/tenantRentStatus')
const { resolveDashboardQuery } = require('../lib/dashboardRouting')
const { normalizePrivateDocumentPath, createExpiringRequestCache } = require('../lib/privateDocument')
const { isDashboardPath } = require('../lib/routeScope')

const id = '123e4567-e89b-42d3-a456-426614174000'
const tenant = { move_in_date:'2026-06-16', rent_amount:10000, status:'active' }
const due = (payments, now = new Date(2026,5,20)) => calculateCanonicalRentDue(tenant, payments, now)
const payment = (overrides = {}) => ({ id:crypto.randomUUID(), status:'success', payment_method:'upi', amount:10000, payment_date:'2026-07-16', ...overrides })

// Owner and Tenant call this same helper with the same tenant-specific records.
const records = [payment()]
assert.deepEqual(calculateCanonicalRentDue(tenant, records, new Date(2026,6,20)), calculateCanonicalRentDue(tenant, records, new Date(2026,6,20)))
assert.equal(due([]).dueDate.toDateString(), new Date(2026,5,16).toDateString())
assert.equal(due([], new Date(2026,5,16)).status, 'due_today')
assert.equal(due([], new Date(2026,6,20)).dueDate.toDateString(), new Date(2026,5,16).toDateString())
assert.equal(due(records, new Date(2026,6,20)).dueDate.toDateString(), new Date(2026,6,16).toDateString())
assert.equal(calculateCanonicalRentDue({ rent_start_date:'2026-06-16', rent_amount:10000, status:'active' }, [], new Date(2026,6,14)).status, 'overdue')
assert.equal(calculateCanonicalRentDue({ rent_start_date:'2026-06-16', rent_amount:10000, status:'active' }, [], new Date(2026,6,14)).daysUntilDue, -28)
for (const excluded of [
  payment({payment_method:'security_deposit'}), payment({payment_method:'pre_booking'}), payment({payment_method:'joining_fee'}), payment({status:'payment_pending'}), payment({status:'rejected'}), payment({amount:5000}),
]) assert.equal(due([excluded]).dueDate.getMonth(), 5)
const duplicate = payment({ id:'same-payment' })
assert.equal(due([duplicate, duplicate]).dueDate.getMonth(), 6)
assert.equal(anchoredDate({year:2026,month:1,day:29},1).getDate(), 28)
assert.equal(anchoredDate({year:2026,month:1,day:30},1).getDate(), 28)
assert.equal(anchoredDate({year:2026,month:1,day:31},1).getDate(), 28)
assert.equal(anchoredDate({year:2024,month:1,day:31},1).getDate(), 29)
assert.equal(formatRentDueLabel({status:'due_soon',daysUntilDue:5}), 'Due in 5 days')
assert.equal(formatRentDueLabel({status:'due_soon',daysUntilDue:1}), 'Due tomorrow')
assert.equal(formatRentDueLabel({status:'due_today',daysUntilDue:0}), 'Due today')
assert.equal(formatRentDueLabel({status:'overdue',daysUntilDue:-1}), 'Overdue by 1 day')
assert.equal(formatRentDueLabel({status:'overdue',daysUntilDue:-3}), 'Overdue by 3 days')
assert.equal(formatRentDueLabel({status:'paid'}), 'Paid')
assert.equal(formatRentDueLabel({status:'inactive',message:'Tenancy inactive'}), 'Tenancy inactive')
assert.equal(formatRentDueLabel({status:'unknown',message:'Due date unavailable'}), 'Due date unavailable')
const rentFixture = daysUntilDue => ({ id:`tenant-${daysUntilDue}`, status:'active', dueStatus:{ status:daysUntilDue < 0 ? 'overdue' : daysUntilDue === 0 ? 'due_today' : 'due_soon', dueDate:new Date(2026,6,14 + daysUntilDue), daysUntilDue, paidPeriods:0 } })
for (const days of [3,2,1]) assert.equal(enrichTenantRentStatus(rentFixture(days)).category, 'upcoming', `${days} days must be upcoming`)
assert.equal(enrichTenantRentStatus(rentFixture(0)).category, 'due')
assert.equal(enrichTenantRentStatus(rentFixture(-1)).category, 'due')
assert.equal(enrichTenantRentStatus({ id:'far-due', status:'active', dueStatus:{ status:'paid', dueDate:new Date(2026,7,16), daysUntilDue:33, paidPeriods:2 } }).category, 'paid')
assert.equal(enrichTenantRentStatus({ id:'paid', status:'active', dueStatus:{ status:'paid', dueDate:null, daysUntilDue:null, paidForCurrentCycle:true } }).category, 'paid')
assert.equal(enrichTenantRentStatus({ id:'inactive', status:'inactive', dueStatus:{ status:'inactive' } }).isActive, false)
assert.equal(enrichTenantRentStatus({ id:'paid-upcoming', status:'active', dueStatus:{ status:'due_soon', daysUntilDue:2, paidPeriods:2 } }).category, 'upcoming')
const rentRows = [rentFixture(3), rentFixture(2), rentFixture(1), rentFixture(0), rentFixture(-1), { id:'far-due', status:'active', dueStatus:{ status:'paid', daysUntilDue:20, paidPeriods:1 } }, { id:'paid', status:'active', dueStatus:{ status:'paid', paidForCurrentCycle:true } }, { id:'inactive', status:'inactive', dueStatus:{ status:'inactive' } }]
assert.equal(filterTenantsByRentStatus(rentRows, 'upcoming').length, 3)
assert.equal(filterTenantsByRentStatus(rentRows, 'due').length, 2)
assert.equal(filterTenantsByRentStatus(rentRows, 'paid').length, 2)
assert.equal(filterTenantsByRentStatus(rentRows, 'all').length, 7)
assert.deepEqual(summarizeTenantRentStatuses(rentRows), { paid:2, due:2, upcoming:3, total:7 })
assert.equal(enrichTenantRentStatus(rentFixture(1)).label, 'Due tomorrow')
assert.equal(enrichTenantRentStatus(rentFixture(-5)).label, 'Overdue by 5 days')
assert.equal(enrichTenantRentStatus({ status:'active', dueStatus:{ status:'paid', daysUntilDue:10, paidPeriods:1 } }).label, 'Paid')
assert.equal(enrichTenantRentStatus({ rent_start_date:'2026-07-12', rent_amount:10000, status:'active' }, [], new Date(2026,6,14)).label, 'Overdue by 2 days')
assert.equal(enrichTenantRentStatus({ rent_start_date:'2026-07-12', rent_amount:10000, status:'active' }, [], new Date(2026,6,14)).category, 'due')
const paidPreviousCycle = [payment({ id:'paid-june-cycle', payment_date:'2026-06-16' })]
assert.equal(enrichTenantRentStatus(tenant, paidPreviousCycle, new Date(2026,6,12)).category, 'paid')
assert.equal(enrichTenantRentStatus(tenant, paidPreviousCycle, new Date(2026,6,13)).label, 'Due in 3 days')
assert.equal(enrichTenantRentStatus(tenant, paidPreviousCycle, new Date(2026,6,13)).category, 'upcoming')
assert.equal(enrichTenantRentStatus(tenant, paidPreviousCycle, new Date(2026,6,14)).label, 'Due in 2 days')
assert.equal(enrichTenantRentStatus(tenant, paidPreviousCycle, new Date(2026,6,14)).category, 'upcoming')
assert.equal(enrichTenantRentStatus(tenant, paidPreviousCycle, new Date(2026,6,15)).label, 'Due tomorrow')
assert.equal(enrichTenantRentStatus(tenant, paidPreviousCycle, new Date(2026,6,16)).category, 'due')
assert.equal(enrichTenantRentStatus(tenant, paidPreviousCycle, new Date(2026,6,17)).label, 'Overdue by 1 day')
assert.equal(enrichTenantRentStatus(tenant, [], new Date(2026,6,14)).dueDate.toDateString(), new Date(2026,5,16).toDateString(), 'oldest unpaid cycle must not advance to the next month')
assert.equal(enrichTenantRentStatus(tenant, [], new Date(2026,6,14)).category, 'due')
assert.equal(enrichTenantRentStatus(tenant, [], new Date(2026,6,14)).label, 'Overdue by 28 days')
const importedPaidBaseline = { id:'its-me', status:'active', move_in_date:'2026-06-16', created_at:'2026-07-11T13:58:10.116607', rent_amount:8000, pending_amount:0, total_paid:0, rent_status:'paid' }
assert.equal(enrichTenantRentStatus(importedPaidBaseline, [], new Date(2026,6,14)).dueDate.toDateString(), new Date(2026,6,16).toDateString(), 'paid imported baseline must cover only cycles before import/creation')
assert.equal(enrichTenantRentStatus(importedPaidBaseline, [], new Date(2026,6,14)).category, 'upcoming')
assert.equal(enrichTenantRentStatus(importedPaidBaseline, [], new Date(2026,6,14)).label, 'Due in 2 days')
const ramFixture = { id:'ram', status:'active', move_in_date:'2026-07-12', created_at:'2026-07-12T07:52:03.040997', rent_amount:8000, pending_amount:8000, total_paid:0, rent_status:'pending' }
assert.equal(enrichTenantRentStatus(ramFixture, [payment({ payment_method:'security_deposit', amount:3000, payment_date:'2026-07-12' })], new Date(2026,6,14)).category, 'due')
assert.equal(enrichTenantRentStatus(ramFixture, [payment({ payment_method:'security_deposit', amount:3000, payment_date:'2026-07-12' })], new Date(2026,6,14)).label, 'Overdue by 2 days')
const expectedProductionRows = [importedPaidBaseline, ramFixture].map(row => ({ ...row, rentSummary: enrichTenantRentStatus(row, row.id === 'ram' ? [payment({ payment_method:'security_deposit', amount:3000, payment_date:'2026-07-12' })] : [], new Date(2026,6,14)) }))
assert.deepEqual(summarizeTenantRentStatuses(expectedProductionRows), { paid:0, due:1, upcoming:1, total:2 })

const mappings = {
  owner: { application:'applications', import:'existing-imports', payment:'rent-payments', complaint:'complaints', 'room-change':'room-change', vacate:'vacate', notice:'notices', membership:'membership', 'archived-tenant':'archived-tenants' },
  tenant: { payment:'payments', notice:'notices', complaint:'complaints', 'room-change':'room-change', vacate:'vacate' },
  admin: { property:'properties', membership:'membership', payment:'payments', application:'applications', complaint:'complaints', 'room-change':'roomchange', vacate:'vacate' },
}
const idKeys = { owner:{ applications:'application_id','existing-imports':'import_id','rent-payments':'payment_id',complaints:'complaint_id','room-change':'request_id',vacate:'request_id',notices:'notice_id',membership:'membership_id','archived-tenants':'tenant_id' }, tenant:{payments:'payment_id',notices:'notice_id',complaints:'complaint_id','room-change':'request_id',vacate:'request_id'}, admin:{properties:'property_id',membership:'membership_id',payments:'payment_id',applications:'application_id',complaints:'complaint_id',roomchange:'request_id',vacate:'request_id'} }
for (const [role, roleMappings] of Object.entries(mappings)) for (const [tab, expected] of Object.entries(roleMappings)) {
  const key = idKeys[role][expected]
  const resolved = resolveDashboardQuery(role, { tab, [key]:id })
  assert.equal(resolved.view, expected); assert.equal(resolved.recordId, id)
  assert.equal(resolveDashboardQuery(role, { tab, [key]:'not-a-uuid' }).recordId, null)
  assert.equal(resolveDashboardQuery(role, { tab:'unknown' }).view, 'overview')
}

assert.equal(normalizePrivateDocumentPath('tenant-documents/property/payments/proof.png'),'property/payments/proof.png')
for (const bad of ['', 'https://example.com/a', 'blob:x', 'data:image/png,x', '../secret', 'bad//path', 'bad?x=1']) assert.equal(normalizePrivateDocumentPath(bad),null)
assert.equal(isDashboardPath('/owner/dashboard'), true)
assert.equal(isDashboardPath('/tenant/dashboard'), true)
assert.equal(isDashboardPath('/admin/dashboard'), true)
for (const publicPath of ['/', '/property/example', '/properties', '/login/tenant', '/register', '/faq']) assert.equal(isDashboardPath(publicPath), false)

const source = relative => fs.readFileSync(path.join(__dirname, '..', relative), 'utf8')
const roomIsAvailable = room => ['vacant', 'occupied'].includes(room.status) && room.current_occupants < room.capacity
const availabilityFixtures = Array.from({ length:9 }, (_, index) => ({ id:index, status:'vacant', current_occupants:index < 2 ? 1 : 0, capacity:2 }))
assert.equal(availabilityFixtures.filter(roomIsAvailable).length, 9, 'tenant count must not be subtracted from room count')
availabilityFixtures[0].current_occupants = 2; availabilityFixtures[1].current_occupants = 2
assert.equal(availabilityFixtures.filter(roomIsAvailable).length, 7, 'full rooms must be excluded')
assert.equal([{status:'vacant',current_occupants:0,capacity:1}].filter(roomIsAvailable).length, 1)
assert.equal([...availabilityFixtures, {status:'archived',current_occupants:0,capacity:2}].filter(roomIsAvailable).length, 7, 'inactive room states must be excluded')
const propertySource = source('pages/property/[id].js')
const ownerDashboardSource = source('pages/owner/dashboard.js')
const globalCssSource = source('styles/globals.css')
assert.match(globalCssSource, /\.dashboard-shell\s*\{[\s\S]*box-sizing:\s*border-box/)
assert.equal(/\.dashboard-shell\s*\{[\s\S]*max-width:\s*100vw/.test(globalCssSource), false, 'dashboard shell must not use 100vw with sidebar padding')
assert.match(ownerDashboardSource, /className="dashboard-content"/, 'desktop owner shell must wrap header and main in a single shrinkable content column')
assert.match(globalCssSource, /\.dashboard-content\s*\{[\s\S]*min-width:\s*0/, 'dashboard content column must be able to shrink')
assert.match(globalCssSource, /\.dashboard-content\s*\{[\s\S]*flex:\s*1 1 auto/, 'desktop dashboard content must take remaining sidebar width through flex')
assert.equal(/\.dashboard-shell\s*\{[^}]*padding-left:\s*15\.\d*rem/.test(globalCssSource), false, 'desktop shell must not offset fixed sidebar with content padding')
assert.equal(/\.dashboard-sidebar\s*\{[^}]*position:\s*fixed/.test(globalCssSource), false, 'desktop sidebar must not be fixed over a padded viewport shell')
for (const unsafeDashboardSelector of ['[class*="p-6"]', '[class*="text-xl"]', '[class*="space-y-6"]']) assert.equal(globalCssSource.includes(unsafeDashboardSelector), false, 'dashboard CSS must not rewrite broad nested Tailwind utility substrings')
assert.equal(ownerDashboardSource.includes('dashboard-main container mx-auto'), false, 'owner dashboard main must not use Tailwind container inside sidebar shell')
assert.equal((ownerDashboardSource.match(/renderOwnerOverview\(\)/g) || []).length <= 2, true, 'owner overview must not have duplicate detached render paths')
assert.match(ownerDashboardSource, /function useDesktopDashboard\(\)/, 'owner dashboard must gate mobile/desktop shells from one media query')
assert.match(ownerDashboardSource, /OWNER_DESKTOP_MIN_WIDTH = 1280/, 'owner desktop shell must wait for enough sidebar + content width')
assert.equal(ownerDashboardSource.includes("matchMedia('(min-width: 1024px)'"), false, 'owner dashboard must not use the unsafe 1024px desktop threshold')
assert.match(globalCssSource, /@media \(min-width:1280px\) \{[\s\S]*\.dashboard-sidebar/, 'desktop sidebar CSS must use the same safe desktop threshold')
assert.equal(/@media \(min-width:1024px\) \{[\s\S]*\.dashboard-sidebar/.test(globalCssSource), false, 'desktop sidebar must not appear at tablet widths')
assert.match(ownerDashboardSource, /if \(isDesktopDashboard === null\) return <DashboardSkeleton cards=\{6\} \/>/, 'owner dashboard must wait for a single shell decision')
assert.equal(/<OwnerMobileDashboard[\s\S]*<main className="dashboard-main[\s\S]*<OwnerMobileDashboard/.test(ownerDashboardSource), false, 'owner overview must not duplicate mobile and desktop overview render paths')
const statsCardsSource = source('components/owner/StatsCards.js')
const mobileOverviewSource = source('components/owner/mobile/OwnerMobileDashboard.js')
assert.equal(statsCardsSource.includes('sm:hidden'), false, 'desktop overview stats must not keep a hidden mobile stats tree mounted')
assert.equal(statsCardsSource.includes('bg-white/60'), false, 'overview stat groups must use opaque card backgrounds')
assert.match(mobileOverviewSource, /stablePaint/, 'mobile owner overview must avoid sticky backdrop blur compositor work')
assert.match(source('pages/_app.js'), /publicAuthEntry/, 'authenticated Back to public login/home must restore the dashboard')
assert.equal(ownerDashboardSource.includes('<div className="lg:hidden">'), false, 'owner mobile shell must not be double-gated by Tailwind lg classes')
assert.equal(ownerDashboardSource.includes('dashboard-main mx-auto hidden'), false, 'owner desktop main must not be double-gated by Tailwind lg classes')
assert.equal(ownerDashboardSource.includes('w-screen'), false, 'owner dashboard shell must not use w-screen inside sidebar layout')
assert.equal(ownerDashboardSource.includes('100vw'), false, 'owner dashboard page must not size content to viewport plus sidebar')
const ownerPhotoApiSource = source('pages/api/owner/tenant-profile-photo.js')
const tenantPhotoApiSource = source('pages/api/tenant/profile-photo.js')
const profilePhotoHelperSource = source('lib/profilePhoto.js')
assert.match(ownerPhotoApiSource, /action === 'batch-sign'/, 'owner tenant photos must be batch signed')
assert.match(ownerPhotoApiSource, /profile-photos\/\$\{tenant\.id\}/, 'owner-updated photos must be tenant scoped')
assert.match(ownerPhotoApiSource, /safeTenantProfilePhotoPath/, 'owner-updated photos must use the shared tenant profile path guard')
assert.match(ownerPhotoApiSource, /safeLegacyProfilePhotoPath/, 'owner fallback photos must use the shared legacy profile path guard')
assert.match(tenantPhotoApiSource, /eq\('user_id', auth\.user\.id\)/, 'tenant photo updates must be scoped to self')
assert.match(tenantPhotoApiSource, /profile-photos\/\$\{tenant\.id\}/, 'tenant photo uploads must be tenant scoped')
assert.match(tenantPhotoApiSource, /safeTenantProfilePhotoPath/, 'tenant photo updates must use the shared tenant profile path guard')
assert.match(profilePhotoHelperSource, /aadhaar\|aadhar/, 'identity/Aadhaar document paths must not be accepted as profile photos')
assert.equal(propertySource.includes('absolute bottom-0 left-0 w-full h-0.5'), false, 'property tabs must not render a detached cross-card divider')
assert.equal(propertySource.includes("from '../../lib/supabase'"), false, 'public property must not initialize the persisted auth client')
assert.equal(source('pages/properties.js').includes("from '../lib/supabase'"), false, 'public browse must not initialize the persisted auth client')
const publicClientSource = source('lib/publicSupabase.js')
assert.match(publicClientSource, /persistSession:false/)
assert.match(publicClientSource, /autoRefreshToken:false/)
assert.match(source('pages/index.js'), /public-login-button/)
assert.match(source('styles/globals.css'), /\.dark \.public-login-button[\s\S]*background:#fff !important/)
assert.match(source('pages/_app.js'), /if \(!isDashboardRoute\) return undefined/)
assert.match(source('next.config.js'), /devIndicators:\s*false/)
const authSource = source('lib/supabase.js')
assert.match(authSource, /if \(sessionRestorePromise\) return sessionRestorePromise/)
assert.match(authSource, /staleSessionRecoveryComplete/)
assert.match(propertySource, /Copy UPI ID/)
assert.match(propertySource, /Copy Phone Number/)
assert.equal(propertySource.includes('Pay with UPI App'), false)
assert.equal(propertySource.includes('upi:\/\/pay'), false)
const payRentSource = source('components/tenant/modals/PayRentModal.js')
assert.equal(payRentSource.includes('Pay with UPI'), false)
assert.equal(payRentSource.includes('upi://pay'), false)
assert.match(payRentSource, /type="button" onClick=\{\(\) => copyUpiId/)
assert.match(payRentSource, /type="button" onClick=\{\(\) => copyUpiPhone/)
assert.match(propertySource, /type="button" aria-label="Copy owner UPI ID"/)
assert.match(propertySource, /type="button" aria-label="Copy owner payment phone number"/)
assert.match(propertySource, /const \[applicationConsent, setApplicationConsent\] = useState\(false\)/)
assert.match(propertySource, /if \(!applicationConsent\)/)
assert.match(propertySource, /if \(!prebookPolicyConsent\)/)
assert.equal(/JSON\.stringify\(\{[\s\S]{0,800}(applicationConsent|prebookPolicyConsent)/.test(propertySource), false, 'UI consent must not be added to visitor payloads')
const registerSource = source('pages/register.js')
assert.match(registerSource, /const \[policyConsent, setPolicyConsent\] = useState\(false\)/)
assert.match(registerSource, /if \(!policyConsent\)/)
assert.equal(/body:\s*JSON\.stringify\(\{[\s\S]{0,800}policyConsent/.test(registerSource), false, 'UI consent must not be added to registration payload')
const mobileRoomsSource = source('components/owner/mobile/OwnerMobileRooms.js')
assert.equal(mobileRoomsSource.includes('⋮</span>'), false, 'mobile three-dot control must not directly delete')
assert.match(mobileRoomsSource, /RoomActionMenu/)
assert.match(source('components/owner/RoomActionMenu.js'), /onEdit\(room\)/)
assert.match(source('components/owner/RoomActionMenu.js'), /onDelete\(room\)/)
const roomMenuSource = source('components/owner/RoomActionMenu.js')
assert.match(roomMenuSource, /createPortal/)
assert.match(roomMenuSource, /minWidth:MENU_WIDTH/)
assert.match(roomMenuSource, /maxWidth:'calc\(100vw - 24px\)'/)
assert.match(roomMenuSource, /whitespace-nowrap/)
assert.match(roomMenuSource, /aria-label="Room actions"/)
assert.match(source('components/owner/mobile/OwnerMobileRooms.js'), /confirm\(`Delete Room/)
assert.match(source('components/tenant/modals/PayRentModal.js'), /dark:bg-slate-950/)
const homeSource = source('pages/index.js')
assert.match(homeSource, /href="\/register" className="[^"]*border-orange-500[^"]*bg-orange-500[^"]*text-white/)
assert.equal(/href="\/register" className="[^"]*disabled/.test(homeSource), false)
const browseSource = source('pages/properties.js')
assert.match(browseSource, /get_public_properties_v2/)
assert.match(browseSource, /available_room_count/)
assert.match(browseSource, /room\$\{property\.availableRooms === 1 \? '' : 's'\} with availability/)
assert.equal(browseSource.includes('totalRooms - property.occupiedRooms'), false)
const migrationSource = source('supabase/migrations/202607120001_public_availability_and_safe_roommates.sql')
assert.match(migrationSource, /current_occupants < room\.capacity/)
assert.match(migrationSource, /tenant\.status in \('active', 'notice_period', 'payment_pending'\)/)
assert.match(migrationSource, /roommate\.property_id/)
assert.match(migrationSource, /requester\.room_id = roommate\.room_id/)
assert.match(migrationSource, /roommate\.id <> requester\.id/)
assert.match(migrationSource, /returns table \(id uuid, name text, phone text\)/)
const tenantContextSource = source('context/TenantContext.js')
assert.match(tenantContextSource, /rpc\('get_my_roommate_contacts'\)/)
assert.equal(tenantContextSource.includes("select('id, name, phone, email, status, room_id, move_in_date')"), false)
const roommateUiSource = source('components/tenant/RoommateContactDialog.js')
assert.match(roommateUiSource, /Phone number unavailable/)
assert.match(roommateUiSource, /href=\{`tel:/)
assert.match(roommateUiSource, /Copy Number/)
for (const privateField of ['email', 'deposit', 'payment', 'address', 'id_proof']) assert.equal(roommateUiSource.includes(privateField), false)
assert.match(publicClientSource, /storageKey:'hostelset-public-anonymous'/)
assert.match(propertySource, /No amenities have been listed for this property yet/)
assert.match(propertySource, /dark:bg-slate-900 dark:text-slate-100/)
const tenantPhotoApi = source('pages/api/tenant/profile-photo.js')
const ownerPhotoApi = source('pages/api/owner/tenant-profile-photo.js')
const tenantPhotoUrlApi = source('pages/api/tenant/profile-photo-url.js')
assert.match(tenantPhotoApi, /role !== 'tenant'|role'\)\.eq\('id', auth\.user\.id\)/)
assert.match(tenantPhotoApi, /eq\('user_id', auth\.user\.id\)/)
assert.match(tenantPhotoApi, /safeTenantProfilePhotoPath/, 'tenant profile photo path must reject non-profile-photo paths')
assert.match(ownerPhotoApi, /properties\(owner_id\)/)
assert.match(ownerPhotoApi, /owner_id/)
assert.match(ownerPhotoApi, /action === 'batch-sign'/)
assert.match(ownerPhotoApi, /safeTenantProfilePhotoPath/)
assert.match(tenantPhotoUrlApi, /profile_photo_path/)
assert.equal(/id_proof[^;]{0,120}profile_photo_path/.test(tenantPhotoUrlApi), false, 'identity document path must not be used as profile photo fallback')

;(async () => {
  let now = 0, calls = 0
  const cache = createExpiringRequestCache({ successTtlMs:100, missingTtlMs:50, now:() => now })
  const missing = async () => { calls += 1; return null }
  await Promise.all([cache.getOrLoad('missing', missing), cache.getOrLoad('missing', missing)])
  assert.equal(calls, 1, 'concurrent signing requests must deduplicate')
  await cache.getOrLoad('missing', missing); assert.equal(calls, 1, 'missing objects must be negatively cached')
  now = 51; await cache.getOrLoad('missing', missing); assert.equal(calls, 2, 'negative cache must be bounded')
  console.log('Reliability helper tests passed')
})().catch(error => { console.error(error); process.exitCode = 1 })
